// <auto-generated />
namespace Excella.Lean.Dal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LinkedEventAndPersonToRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkedEventAndPersonToRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201304180211507_LinkedEventAndPersonToRequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
